EasyBoni/Controllers/RestaurantController.cs
using EasyBoni.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EasyBoni.Models.DAL;
using EasyBoni.Models.View;

namespace EasyBoni.Controllers
{
    public class RestaurantController : Controller
    {
        private RestaurantsManager model = RestaurantsManager.Instance;

        public ActionResult Map()
        {
            return View();
        }

        // GET: Restaurant
        public ActionResult List(string query, RestaurantsOrder order = RestaurantsOrder.Name)
        {
            IEnumerable<Restaurant> restaurants = model.Restaurants;

            if (!string.IsNullOrWhiteSpace(query))
            {
                restaurants = restaurants.Where(r => r.Name.ToLower().Contains(query.ToLower()));
            }

            switch (order)
            {
                case RestaurantsOrder.Name:
                    restaurants = restaurants.OrderBy(r => r.Name);
                    break;
                case RestaurantsOrder.Price:
                    restaurants = restaurants.OrderBy(r => r.Price);
                    break;
                case RestaurantsOrder.Rating:
                    restaurants = restaurants.OrderByDescending(r => r.Rating);
                    break;
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView("_RestaurantsList", restaurants);
            }

            return View(restaurants);
        }

        public ActionResult GetList()
        {
            return Json(model.Restaurants, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public async Task<ActionResult> AddRating(int id, int value)
        {
            ApplicationDbContext db = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            ApplicationUserManager manager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            ApplicationUser user = await manager.FindByNameAsync(User.Identity.Name);

            var rating = new Rating()
            {
                RestaurantID = id,
                User = user,
                Value = value
            };

            db.Ratings.Add(rating);
            await db.SaveChangesAsync();

            Restaurant restaurant = model.Restaurants.Find(r => r.ID == id);
            
            return PartialView("_RatingPartial", restaurant);
        }
    }
}

EasyBoni/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - EasyBoni ASP.NET MVC Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("EasyBoni ASP.NET", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Map", "Map", "Restaurant")</li>
                    <li>@Html.ActionLink("List", "List", "Restaurant")</li>
                </ul>
                @RenderSection("header", required: false)

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Marian Rusnak @DateTime.Now.Year - EasyBoni ASP.NET MVC Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>